// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7gXpo2T28qd3v8vYXPtDNDeNWI5-4GU',
    appId: '1:921212213787:web:b172a3e3a492f56857f6be',
    messagingSenderId: '921212213787',
    projectId: 'tikeapp-bb839',
    authDomain: 'tikeapp-bb839.firebaseapp.com',
    storageBucket: 'tikeapp-bb839.firebasestorage.app',
    measurementId: 'G-6J8PHT28WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCME7Z5H0d1p-fS-kzbJ0MqQBiOmByaL2g',
    appId: '1:921212213787:android:63d4f2e4e1359de157f6be',
    messagingSenderId: '921212213787',
    projectId: 'tikeapp-bb839',
    storageBucket: 'tikeapp-bb839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHzlixRqNeXc7EHVcNiTABP3oBA5XPRY',
    appId: '1:921212213787:ios:3025ba3a4c6f842557f6be',
    messagingSenderId: '921212213787',
    projectId: 'tikeapp-bb839',
    storageBucket: 'tikeapp-bb839.firebasestorage.app',
    iosClientId: '921212213787-ughm3hu9kmhag75qudnp01nabbuhupi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTickets',
  );

}